// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxnwvlmxgwtxovurutqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bnd2bG14Z3d0eG92dXJ1dHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTk1NzksImV4cCI6MjA2NTE5NTU3OX0.mcRWeBkX1mAKgR5ep1KTznzxUW8lswXdEJolw9xkdsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);